site_name: Influenciae

#google_analytics:
#  - UA-132343476-2
#  - auto

nav:
  - Home: index.md
  - Influence Functions:
      - First Order Influence Calculator: api/first_order_influence_calculator.md
      - Second Order Influence Calculator: api/second_order_influence_calculator.md
  - Representer Point Selection:
      - Representer Point Selection - L2: api/rps_l2.md
      - Representer Point Selection - LJE: api/rps_lje.md
  - TracIn: api/tracin.md
  - Benchmarks: api/benchmarks.md

theme:
  name: "material"
  logo: assets/LogoInfluenciae.png
  favicon: assets/LogoInfluenciae.png
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
plugins:
  - numkdoc
  - search

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
      toc_depth: 1-2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js
  - js/custom.js

repo_name: "deel-ai/influenciae"
repo_url: "https://github.com/deel-ai/influenciae"
